import type { StudioState, PortDescriptor, PortEndpoint } from '../../../packages/studio-model/src/index.js';
import type { ViewportLayout } from '../../../packages/project-model/src/index.js';
import { activeGraphDefinition, checkPortConnection, connectPorts, disconnectEdge, ensureNodeLayout, enterNodeGroup, graphEdgeKey, moveNode, parseNodeGroupTypeId, resolveNodePorts, selectEdge, selectNode, setViewport, selectedGraphDocument, selectedGraphLayout } from '../../../packages/studio-model/src/index.js';
import { renderNodeView, SVG_NS } from './node-view.js';
export function panViewport(viewport:ViewportLayout,dx:number,dy:number):ViewportLayout{return {x:viewport.x+dx,y:viewport.y+dy,zoom:viewport.zoom}}
export function renderGraphCanvas(container:HTMLElement,state:StudioState,onChange:(state:StudioState)=>void,onDiagnostics?:(messages:readonly string[])=>void):void{
  container.replaceChildren();const active=activeGraphDefinition(state);if(!active){container.textContent='No graph selected';return}
  const nested=(state.graphSelection?.nodeGroupPath.length??0)>0;let working=state;if(!nested)for(const node of active.nodes) working=ensureNodeLayout(working,node.id);
  const persisted=selectedGraphLayout(working);const virtualNodes=Object.fromEntries(active.nodes.map((node,index)=>[node.id,persisted?.nodes[node.id]??{x:(index%4)*240,y:Math.floor(index/4)*150}]));const layout=nested?{schema_version:1 as const,graph_id:active.id,nodes:virtualNodes}:{...(persisted??{schema_version:1 as const,graph_id:active.id,nodes:{}}),nodes:virtualNodes};if(working!==state)onChange(working);
  const svg=document.createElementNS(SVG_NS,'svg');svg.classList.add('graph-svg');svg.setAttribute('width','100%');svg.setAttribute('height','100%');container.append(svg);
  const viewport=document.createElementNS(SVG_NS,'g');const view=layout?.viewport??{x:0,y:0,zoom:1};viewport.setAttribute('transform',`translate(${view.x} ${view.y}) scale(${view.zoom})`);svg.append(viewport);
  let pending:PortEndpoint|undefined;let panStart:{x:number;y:number;clientX:number;clientY:number}|undefined;
  for(const edge of active.edges){const a=layout?.nodes[edge.sourceNodeId],b=layout?.nodes[edge.targetNodeId];if(!a||!b)continue;const line=document.createElementNS(SVG_NS,'line');line.setAttribute('x1',String(a.x+(a.width??210)));line.setAttribute('y1',String(a.y+62));line.setAttribute('x2',String(b.x));line.setAttribute('y2',String(b.y+62));line.classList.add('graph-edge');const key=graphEdgeKey(edge);line.dataset.edgeKey=key;if(state.selection.kind==='edge'&&state.selection.id===key)line.classList.add('selected');line.addEventListener('click',event=>{event.stopPropagation();onChange(selectEdge(working,key))});viewport.append(line)}
  for(const node of active.nodes){const pos=layout?.nodes[node.id]??{x:0,y:0};const ports=resolveNodePorts(working,node.id);const el=renderNodeView(node,pos,state.selection.kind==='node'&&state.selection.id===node.id,ports,{
    onPortDown:(port,event)=>{if(port.direction==='output'){event.stopPropagation();pending={nodeId:port.nodeId,portId:port.portId}}},
    onPortUp:(port,event)=>{if(!pending||port.direction!=='input')return;event.stopPropagation();const target={nodeId:port.nodeId,portId:port.portId};const result=connectPorts(working,pending,target);pending=undefined;if(result.diagnostics.length)onDiagnostics?.(result.diagnostics.map(d=>d.message));else onChange(result.state)},
    onPortEnter:(port,socket)=>{if(!pending||port.direction!=='input')return;const diagnostics=checkPortConnection(working,pending,{nodeId:port.nodeId,portId:port.portId});socket.classList.toggle('connection-refused',diagnostics.length>0);socket.classList.toggle('connection-allowed',diagnostics.length===0)},
    onPortLeave:(_port,socket)=>socket.classList.remove('connection-refused','connection-allowed')
  });el.addEventListener('dblclick',event=>{const groupId=parseNodeGroupTypeId(node.typeId);if(groupId){event.stopPropagation();onChange(enterNodeGroup(working,groupId))}});let start:{x:number;y:number;px:number;py:number}|undefined;el.addEventListener('pointerdown',event=>{if((event.target as Element).classList.contains('port-socket'))return;event.stopPropagation();el.setPointerCapture(event.pointerId);start={x:pos.x,y:pos.y,px:event.clientX,py:event.clientY};onChange(selectNode(working,node.id))});el.addEventListener('pointermove',event=>{if(!start)return;if(!nested)onChange(moveNode(working,node.id,start.x+(event.clientX-start.px)/view.zoom,start.y+(event.clientY-start.py)/view.zoom))});el.addEventListener('pointerup',()=>{start=undefined});viewport.append(el)}
  svg.addEventListener('pointerdown',event=>{if(event.target!==svg)return;panStart={x:view.x,y:view.y,clientX:event.clientX,clientY:event.clientY};svg.setPointerCapture(event.pointerId)});svg.addEventListener('pointermove',event=>{if(!panStart)return;const next=panViewport({x:panStart.x,y:panStart.y,zoom:view.zoom},event.clientX-panStart.clientX,event.clientY-panStart.clientY);onChange(setViewport(working,next))});svg.addEventListener('pointerup',()=>{panStart=undefined});svg.addEventListener('click',()=>onChange({...working,selection:{kind:'none'}}));svg.addEventListener('wheel',event=>{event.preventDefault();const next=Math.max(.35,Math.min(2.5,view.zoom*(event.deltaY>0?.9:1.1)));onChange(setViewport(working,{...view,zoom:next}))},{passive:false});
  container.onkeydown=event=>{if((event.key==='Delete'||event.key==='Backspace')&&state.selection.kind==='edge'&&state.selection.id){const result=disconnectEdge(working,state.selection.id);if(result.diagnostics.length)onDiagnostics?.(result.diagnostics.map(d=>d.message));else onChange({...result.state,selection:{kind:'none'}})}};
}
