import type { NodeCatalogEntry, StudioState } from '../../../packages/studio-model/src/index.js';
import { buildNodeCatalog, searchNodeCatalog } from '../../../packages/studio-model/src/index.js';
export interface NodeShelfController { close():void; element:HTMLElement; }
export function openNodeShelf(state:StudioState,position:{x:number;y:number},onPick:(entry:NodeCatalogEntry)=>void):NodeShelfController{
  const root=document.createElement('div');root.className='node-shelf';root.style.left=`${position.x}px`;root.style.top=`${position.y}px`;
  const input=document.createElement('input');input.className='node-shelf-search';input.placeholder='Search nodes…';root.append(input);
  const list=document.createElement('div');list.className='node-shelf-list';root.append(list);let active=0;const catalog=buildNodeCatalog(state);
  const render=()=>{const entries=searchNodeCatalog(catalog,input.value);list.replaceChildren();if(!input.value){for(const source of ['primitive','node-group'] as const){const heading=document.createElement('div');heading.className='node-shelf-heading';heading.textContent=source==='primitive'?'Primitives':'Node Groups';list.append(heading);for(const entry of entries.filter(e=>e.source===source).slice(0,12))list.append(row(entry))}}else entries.slice(0,20).forEach(entry=>list.append(row(entry)));function row(entry:NodeCatalogEntry){const button=document.createElement('button');button.className='node-shelf-item';button.dataset.entryId=entry.id;const main=document.createElement('span');main.textContent=entry.label;const meta=document.createElement('small');meta.textContent=entry.source==='primitive'?entry.category??'Primitive':'Node Group';button.append(main,meta);button.onclick=()=>onPick(entry);return button};const buttons=[...list.querySelectorAll<HTMLButtonElement>('.node-shelf-item')];active=Math.min(active,Math.max(0,buttons.length-1));buttons[active]?.classList.add('active')};
  input.addEventListener('input',()=>{active=0;render()});input.addEventListener('keydown',event=>{const buttons=[...list.querySelectorAll<HTMLButtonElement>('.node-shelf-item')];if(event.key==='ArrowDown'){event.preventDefault();active=Math.min(buttons.length-1,active+1);render()}else if(event.key==='ArrowUp'){event.preventDefault();active=Math.max(0,active-1);render()}else if(event.key==='Enter'){event.preventDefault();buttons[active]?.click()}else if(event.key==='Escape'){event.preventDefault();root.remove()}});render();document.body.append(root);queueMicrotask(()=>input.focus());return {element:root,close:()=>root.remove()};
}
