import type { GraphNode } from '../../../packages/runtime/src/index.js';
import type { NodeLayout } from '../../../packages/project-model/src/index.js';
import type { PortDescriptor } from '../../../packages/studio-model/src/index.js';
export const SVG_NS='http://www.w3.org/2000/svg';
/** Compact on-canvas labels; the socket's SVG <title> retains full port/type details. */
const canvasLabel=(text:string,max=14)=>text.length>max?`${text.slice(0,max-1)}…`:text;
export interface NodeViewHandlers { readonly onPortDown?:(port:PortDescriptor,event:PointerEvent)=>void; readonly onPortUp?:(port:PortDescriptor,event:PointerEvent)=>void; readonly onPortEnter?:(port:PortDescriptor,el:SVGElement)=>void; readonly onPortLeave?:(port:PortDescriptor,el:SVGElement)=>void; }
export function renderNodeView(node:GraphNode,layout:NodeLayout,selected:boolean,ports:readonly PortDescriptor[]=[],handlers:NodeViewHandlers={}):SVGGElement{
  const width=layout.width??210;const height=Math.max(layout.height??92,64+Math.max(ports.filter(p=>p.direction==='input').length,ports.filter(p=>p.direction==='output').length)*22);
  const g=document.createElementNS(SVG_NS,'g');g.classList.add('graph-node');if(node.typeId.startsWith('node-group:'))g.classList.add('node-group-instance');if(selected)g.classList.add('selected');g.dataset.nodeId=node.id;g.setAttribute('transform',`translate(${layout.x} ${layout.y})`);
  const rect=document.createElementNS(SVG_NS,'rect');rect.setAttribute('width',String(width));rect.setAttribute('height',String(height));rect.setAttribute('rx','10');rect.classList.add('node-body');g.append(rect);
  const title=document.createElementNS(SVG_NS,'text');title.setAttribute('x','14');title.setAttribute('y','22');title.classList.add('node-title');title.textContent=canvasLabel(node.typeId,27);const fullTitle=document.createElementNS(SVG_NS,'title');fullTitle.textContent=node.typeId;title.append(fullTitle);g.append(title);
  const id=document.createElementNS(SVG_NS,'text');id.setAttribute('x','14');id.setAttribute('y','42');id.classList.add('node-id');id.textContent=node.id;g.append(id);
  for(const direction of ['input','output'] as const){const list=ports.filter(port=>port.direction===direction);list.forEach((port,index)=>{const y=62+index*22;const x=direction==='input'?0:width;const socket=port.cardinality==='MANY'?document.createElementNS(SVG_NS,'rect'):document.createElementNS(SVG_NS,'circle');socket.classList.add('port-socket',direction,`cardinality-${port.cardinality.toLowerCase()}`);socket.dataset.nodeId=node.id;socket.dataset.portId=port.portId;socket.dataset.direction=port.direction;if(socket.tagName==='rect'){socket.setAttribute('x',String(x-5));socket.setAttribute('y',String(y-5));socket.setAttribute('width','10');socket.setAttribute('height','10');socket.setAttribute('rx','2')}else{socket.setAttribute('cx',String(x));socket.setAttribute('cy',String(y));socket.setAttribute('r','5')};const tip=document.createElementNS(SVG_NS,'title');tip.textContent=`${port.direction} • ${port.cardinality} • ${port.acceptedTypes.join(' | ')}`;socket.append(tip);socket.addEventListener('pointerdown',e=>handlers.onPortDown?.(port,e as PointerEvent));socket.addEventListener('pointerup',e=>handlers.onPortUp?.(port,e as PointerEvent));socket.addEventListener('pointerenter',()=>handlers.onPortEnter?.(port,socket));socket.addEventListener('pointerleave',()=>handlers.onPortLeave?.(port,socket));g.append(socket);const label=document.createElementNS(SVG_NS,'text');label.setAttribute('x',String(direction==='input'?10:width-10));label.setAttribute('y',String(y+3));label.setAttribute('text-anchor',direction==='input'?'start':'end');label.classList.add('port-label');label.textContent=canvasLabel(port.portId);g.append(label)})}
  return g;
}
